<a href="https://colab.research.google.com/github/Alena-Ab/lingdata/blob/main/homework22-23/hw1_2025.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ДОМАШНЯЯ РАБОТА №1 (pandas)
### Требования к оформлению тетрадок прописаны в первой тетрадке учебных материалов.

### **Мягкий дедлайн: 6 октября.**
### **Жёсткий дедлайн: 11 октября.**
### После мягкого дедлайна за каждое задание можно получить только половину баллов. После жёсткого дедлайна работы не принимаются.


### **Критерии оценивания.** За каждую часть можно получить по 2 балла. 9/10 баллов можно получить только в том случае, если Вы не просто правильно выполните задания, но также построите графики и сделаете какие-то выводы на основе полученных результатов. Напишите, что кажется Вам закономерным/необычным. Какие ещё вопросы Вы бы задали к данным и как (предложите фреймворк кода)? Подумайте об ограничениях, особенностях данных и тд.

### Удачи!

______________________________________________________________________________________________________________________________

### Вам предстоит проанализировать [датасет](https://www.kaggle.com/datasets/adilshamim8/educational-backgrounds-of-successful-people), содержащий сведения об образовании известных успешных людей.

## ЧАСТЬ 1: базовый анализ и очистка данных

#### Загрузите датасет и узнайте его размер, типы данных в столбцах.

In [3]:
import pandas as pd

df = pd.read_csv("successful_educations.csv")

In [4]:
df.shape

(125, 10)

In [5]:
df.columns

Index(['Name', 'Profession', 'Degree', 'Field', 'Institution',
       'Graduation Year', 'Country', 'University Global Ranking',
       'GPA (or Equivalent)', 'Scholarship/Award'],
      dtype='object')

#### Найдите количество пропущенных значений в каждом столбце. Выведите первые 5 строк, последние 3 строки и 2 случайные строки, а также с 10 по 15 строки.

In [12]:
NaN = df.isnull().sum()
print(NaN)

Name                          0
Profession                    3
Degree                        9
Field                        10
Institution                  10
Graduation Year              16
Country                       4
University Global Ranking    45
GPA (or Equivalent)          39
Scholarship/Award            40
dtype: int64

In [7]:
df.head(5)

,Name,Profession,Degree,Field,Institution,Graduation Year,Country,University Global Ranking,GPA (or Equivalent),Scholarship/Award
0,Elon Musk,Entrepreneur,Bachelor of Science,Physics & Economics,University of Pennsylvania,1997,USA,13,3.7,Dean’s List
1,Bill Gates,Entrepreneur,Dropped Out,computer science,Harvard University,1975,USA,5,NaN,Dean’s List
2,Sundar Pichai,Tech Executive,Master of Science,Material Sciences and Engineering,Stanford University,1995,USA,3,3.8,Fellowship in Engineering
3,Sheryl Sandberg,Tech Executive,Master of Business Administration,Business Administration,Harvard Business School,1995,USA,2,3.9,Hoover Fellowship
4,Jeff Bezos,Entrepreneur,Bachelor of Science,Computer Science and Electrical Engineering,Princeton University,1986,USA,16,3.6,Marquis Scholar

In [8]:
df.tail(3)

,Name,Profession,Degree,Field,Institution,Graduation Year,Country,University Global Ranking,GPA (or Equivalent),Scholarship/Award
122,Aliko Dangote,Business,Bachelor's Degree,Business Administration,Al-Azhar University,1977,Nigeria,NaN,NaN,NaN
123,Gennady Timchenko,Business,NaN,NaN,NaN,NaN,Indonesia,NaN,NaN,NaN
124,Idan Ofer,Business,Bachelor's Degree,Economics and Management,London School of Economics,1987,United Kingdom,49,NaN,NaN

In [9]:
df.sample(2)

,Name,Profession,Degree,Field,Institution,Graduation Year,Country,University Global Ranking,GPA (or Equivalent),Scholarship/Award
47,Mindy Kaling,Actor/Writer,Bachelor,Playwriting,Dartmouth College,2001,USA,12,3.7,Eleanor Frost Prize
25,Jack Ma,Tech CEO,Bachelor,English,Hangzhou Normal University,1988,China,NaN,3.6,Honorary PhD

In [11]:
df.loc[10:15]

,Name,Profession,Degree,Field,Institution,Graduation Year,Country,University Global Ranking,GPA (or Equivalent),Scholarship/Award
10,Marie Curie,Scientist,Doctor of Philosophy,Physics,University of Paris,1903,France,35,NaN,Nobel Fellowship
11,Barack Obama,Politician,Juris Doctor,Law,Harvard Law School,1991,USA,2,3.1,Harvard Law Review Editor
12,Tim Cook,Tech Executive,Master of Business Administration,Business Administration,Fuqua School of Business (Duke University),1988,USA,26,3.8,Fuqua Scholar
13,Serena Williams,Athlete,Bachelor of Science,Business Administration,University of California,2021,USA,40,3.6,Student-Athlete Academic Award
14,Sergey Brin,Entrepreneur,Master of Science,Computer Science,Stanford University,1995,USA,3,3.9,National Science Foundation Fellowship
15,Larry Page,Entrepreneur,Master of Science,Computer Engineering,Stanford University,1995,USA,3,3.9,NSF Graduate Fellowship

#### Удалите колонку Scholarship/Award.

In [16]:
df = df.drop(columns=['Scholarship/Award'])

KeyError: "['Scholarship/Award'] not found in axis"

#### Переименуйте колонку "Profession", заменив на "Occupation".

####  Соберите статистику по столбцу GPA при помощи метода .describe(), не забудьте про NA.

#### Заполните пропуски в столбце GPA средним значением.

## ЧАСТЬ 2: фильтрация и поиск

#### Выведите всех выпускников Лиги плюща (Harvard University, Yale University, Princeton University, Columbia University, Brown University, University of Pennsylvania, Cornell University, Dartmouth College).

#### Найдите всех нобелевских лауреатов и выведите только их имена, страну и род деятельности.

## ЧАСТЬ 3: создание и преобразование столбцов

#### Создайте колонку 'Top_University' со значением True для университетов, входящих в топ-50. Обратите внимание на значения типа "231–240".

#### Создайте колонку Academic_Performance, в которую внесите значение:
#### - "High", если GPA выше 3.5 баллов,
#### - "Medium", если GPA от 3 до 3.49 баллов,
#### - "Low", если GPA ниже 3 баллов.

#### Посмотрите на уникальные значения в колонке Degree и приведите их к единообразию (Bachelor of Science -> Bachelor).

## ЧАСТЬ 4: агрегация и группировка

#### Найдите топ-5 университетов по количеству выпускников в датасете.

#### Найдите топ-5 самых популярных областей обучения среди предпринимателей.

#### Определите топ-5 стран с самыми высокими значениями GPA.

#### Сгруппируйте записи по профессиям и посчитайте:
#### - количество людей в каждой профессии,
#### - средний GPA для каждой профессии,
#### - количество людей с разными уровнями образования для каждой профессии.

#### Сгруппируйте данные сначала по стране и профессии. Посчитайте:
#### - количество людей,
#### - средний GPA.

#### Удалите NA в столбце с годом выпуска, преобразуйте значения в тип datetime64, сделайте столбец индексом датафрейма и сгруппируйте по десятилетиям (метод .resample). Посчитайте:
#### - количество выпускников в каждом десятилетии,
#### - наиболее популярную область обучения для каждого десятилетия,
#### - средний GPA.
#### PS: сначала избавьтесь от NA в соответствующей колонке.